### ISSUE TITLE
Buildah is failing due to env variable not being resolved

### ISSUE THREAD

**Issue by andrew-suh** [ibm-cloud-architecture/devops-demo-sample-ace-project#1]
Command used:
      buildah bud --build-arg PROJECT1=$PROJECT --tls-verify=$(inputs.params.TLSVERIFY) --layers -f $(inputs.params.dockerfileLocation) -t $(outputs.resources.image.url):$(inputs.params.buildversion)-amd64 $(inputs.params.CONTEXT)

**Comment by andrew-suh** [comment]
This was related the the ENV and ARG argument problem in the Dockerfile and has been resolved.

**Comment by hollisc** [comment]
Closing per update above.
